main: execute_mn.py
	sudo python execute_mn.py 100 ./src/tmp.txt ./dst/tmp1.txt
sender: 
	#python3 sender.py 192.168.0.33 100 ./src/EMMA.word ./dst/tmp1.txt
	python3 sender.py  127.0.0.1 100 ./src/EMMA.word ~/dst/tmp1.txt
receiver:
	python3 receiver.py 192.168.0.33 
